### PR TITLE
Add build GH action

### PR DESCRIPTION
**Pull request by PimvanderLoos**
- Added a GitHub actions task to build this project and apply all the static analysis tools we're using for all commits/PRs to the master branch.
- Updated some dependencies to get the action to work.

### CODE REVIEW

**Comment by PimvanderLoos** [comment]
This should make it a bit easier to verify PRs going forward. Especially for stuff like Dependabot. 
Currently, there are several Dependabot PRs that aren't merged, as at least 1 of them causes issues because of a since-resolved bug in ErrorProne for Java 17 that hasn't been released yet.

**Comment by PimvanderLoos** [comment]
This should make it a bit easier to verify PRs going forward. Especially for stuff like Dependabot.
Currently, there are several Dependabot PRs that aren't merged, as at least 1 of them causes issues because of a since-resolved bug in ErrorProne for Java 17 that hasn't been released yet.

**Comment by PimvanderLoos** [comment]
This should make it a bit easier to verify PRs going forward. Especially for stuff like Dependabot.
Currently, there are several Dependabot PRs that aren't merged, as at least 1 of them causes issues because of a since-resolved bug in ErrorProne for Java 17 that hasn't been released yet.

**Comment by PimvanderLoos** [comment]
aaaaaaaaaaaaaaaaaaaaa

**Comment by PimvanderLoos** [comment]
This should make it a bit easier to verify PRs going forward. Especially for stuff like Dependabot.
Currently, there are several Dependabot PRs that aren't merged, as at least 1 of them causes issues because of a since-resolved bug in ErrorProne for Java 17 that hasn't been released yet.

**Comment by PimvanderLoos** [comment]
This should make it a bit easier to verify PRs going forward. Especially for stuff like Dependabot.
Currently, there are several Dependabot PRs that aren't merged, as at least 1 of them causes issues because of a since-resolved bug in ErrorProne for Java 17 that hasn't been released yet.

**Comment by bonn2** [comment]
Would it also be possible to upload the build artifact? That way once stuff becomes more stable we could do easier testing without everyone needing to setup the dev environment and build the project.

**Comment by PimvanderLoos** [comment]
Yeah, I was considering doing that. However, the issue is that the plugin only runs on a modified version of Spigot at the moment. This is because it only runs on 1.15 with Java 17, which isn't supported on Spigot 1.15.2., so for testing, I use a Spigot jar which I modified with Recaf to remove the Java version check (as it doesn't apply to our (or most any) situation).
Also, even if it does run, there's the issue that it doesn't have a GUI or commands to interact with it.

This is why I ultimately decided not to upload the jar, as it might give people false hope that the jar provides anything useful. However, I do agree that it'd be nice to have eventually, and given that there's most likely never going to be a "right time" to start providing the jar, we might as well get out ahead of it and do it right now.

**Comment by rainbowdashlabs** [comment]
> I use a Spigot jar which I modified with Recaf to remove the Java version check (as it doesn't apply to our (or most any) situation).

Paper has a flag to disable this check. that might be enough for testing purposes anyway. Just add a disclaimer and you are done.


> Especially for stuff like Dependabot

I switched all my repositories to renovate. Had a very good experience with it yet. It is way better than dependabot.

Ps.: Still hope to see gradle here at some point :P

**Comment by PimvanderLoos** [comment]
> Paper has a flag to disable this check. that might be enough for testing purposes anyway. Just add a disclaimer and you are done.

Yeah, `-DPaper.IgnoreJavaVersion=true`, but iirc that was only added in 1.16. Don't quote me on that, though ;)

> I switched all my repositories to renovate. Had a very good experience with it yet. It is way better than dependabot.

Took a quick look at what the difference is, and I does look like it's more what I'm looking for.

> Ps.: Still hope to see gradle here at some point :P

As long as Maven works I have no intention to switch :D

**Comment by rainbowdashlabs** [comment]
Just out of curiosity:
Where are those files uploaded at? I dont see any way to access it outside of jobs 🤔 
Probably a upload to some online repository would be better. Probably with an publish task

**Comment by bonn2** [comment]
> Just out of curiosity: Where are those files uploaded at? I dont see any way to access it outside of jobs 🤔 Probably a upload to some online repository would be better. Probably with an publish task

The per-commit builds would be found under the "Actions" tab at the top, then select a commit, then at the bottom in the artifacts section.

**Comment by PimvanderLoos** [comment]
> The per-commit builds would be found under the "Actions" tab at the top, then select a commit, then at the bottom in the artifacts section.

I noticed that the `DoorTypes.zip` file was massive (almost 16MB), which was caused by each type shading in a whole bunch of stuff that wasn't needed. While it might not be directly related to this PR, I fixed this issue here regardless, as we now have correct artifacts available, which _is_ an important part of this PR.

> Probably a upload to some online repository would be better. Probably with an publish task

For now, I think having it hosted in the actions build should be fine. Once we get closer to release I'll host it on some repo for easy access via Maven/Gradle. However, I wouldn't recommend developing against the current builds anyway, as I'm changing stuff whenever needed with absolutely no regard for stability in any way.

**Comment by PimvanderLoos** [comment]
I think this should basically be ready now. Anyone got any further comments?
I'll look into Renovate vs Dependabot for another PR.

**Comment by bonn2** [comment]
All looks good to me

**Pull request merged**
